### ISSUE TITLE
Create new game procedure

### ISSUE THREAD

**Issue by Anana237** [QuizFight/QuizFight#43]
send MsgCreateGame to Backend and manage response

Ablauf Createn:
- [x] Client -> Master : MsgCreateGame
- [x] Client <- Master : MsgTransferToGameServer
- [x] Client -> Slave  : MsgCreateGame
- [x] Client <- Slave  : GameInfo

Abschluss: Client zeigt GameInfo

**Comment by Conriano** [comment]
Ablauf Createn:
Client -> Master : MsgCreateGame
Client <- Master : MsgTransferToGameServer
Client -> Slave  : MsgCreateGame
Client <- Slave  : GameInfo

Abschluss: Client zeigt GameInfo

**Comment by Conriano** [comment]
<details>
<summary>Spoiler</summary>
ASDFGHJKLÖ
</details>
